name: Build Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker Login
      run: echo "${{ secrets.CR_PAT }}" | docker login -u ${{ secrets.CR_USER }} --password-stdin

    - name: Build docker container
      run: docker build -t ${{ secrets.CR_REPO }}/sudoku-solver:latest . --file=build/Dockerfile

    - name: Push docker container
      run: docker push ${{ secrets.CR_REPO }}/sudoku-solver:latest

    - name: Docker Logout
      run: docker logout
